#############################################################################
# Makefile for building: adc_calibration
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  adc_calibration.pro
# Template: app
# Command: /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/qmake -o Makefile adc_calibration.pro -spec devices/linux-arm-xilinx-zynq-g++ CONFIG+=debug CONFIG-=qml_debug CONFIG-=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc
CXX           = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-g++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_CORE_LIB
CFLAGS        = -pipe -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mfpu=vfpv3-d16 -pipe -fomit-frame-pointer --sysroot=/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot -g -Wall -W -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-psabi -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/include -DZYNQ -pipe -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mfpu=vfpv3-d16 -pipe -fomit-frame-pointer --sysroot=/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot -g -std=gnu++11 -Wall -W -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include -I../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore -I. -I../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++
QMAKE         = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = adc_calibration1.0.0
DISTDIR = /home/sukhval/PROJ/adc_calibration/.tmp/adc_calibration1.0.0
LINK          = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-g++
LFLAGS        = -L/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/lib --sysroot=/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot -Wl,--gc-sections
LIBS          = $(SUBLIBS) /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/lib/libQt5Core.a -lm /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/lib/libqtpcre2.a /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/lib/libdl.so -lpthread   
AR            = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = adc_proc.cpp \
		main.cpp moc_adc_proc.cpp
OBJECTS       = adc_proc.o \
		main.o \
		moc_adc_proc.o
DIST          = ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_pre.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/linux.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/sanitize.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base-unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-base.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qdevice.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/device_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qconfig.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_zlib_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_functions.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exclusive_builds.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/toolchain.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_pre.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resolve_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_post.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/warn_on.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/gc_binaries.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resources.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/moc.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/unix/thread.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qmake_use.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/file_copies.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/testcase_targets.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exceptions.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/yacc.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/lex.prf \
		adc_calibration.pro adc_proc.h \
		axireg.h \
		system_global.h adc_proc.cpp \
		main.cpp
QMAKE_TARGET  = adc_calibration
DESTDIR       = 
TARGET        = adc_calibration


first: all
####### Build rules

adc_calibration: /home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/lib/libQt5Core.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: adc_calibration.pro ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_pre.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/linux.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/sanitize.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base-unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-base.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-unix.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qdevice.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/device_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qconfig.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_zlib_private.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_functions.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exclusive_builds.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/toolchain.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_pre.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resolve_config.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_post.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/warn_on.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/gc_binaries.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resources.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/moc.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/unix/thread.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qmake_use.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/file_copies.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/testcase_targets.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exceptions.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/yacc.prf \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/lex.prf \
		adc_calibration.pro \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/lib/libQt5Core.prl
	$(QMAKE) -o Makefile adc_calibration.pro -spec devices/linux-arm-xilinx-zynq-g++ CONFIG+=debug CONFIG-=qml_debug CONFIG-=qtquickcompiler
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_pre.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/unix.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/linux.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/sanitize.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/gcc-base-unix.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-base.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/common/g++-unix.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qdevice.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/device_config.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/qconfig.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_concurrent_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_core_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_dbus_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_network_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_networkauth_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_nfc_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_positioning_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_purchasing_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qml_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_repparser_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_script_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_scxml_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sensors_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialbus_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_serialport_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_sql_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_testlib_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_webchannel_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_websockets_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xml_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_lib_zlib_private.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qnmbearer.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qsqlite.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_functions.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt_config.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/spec_post.prf:
.qmake.stash:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exclusive_builds.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/toolchain.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_pre.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resolve_config.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/default_post.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/warn_on.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qt.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/gc_binaries.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/resources.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/moc.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/unix/thread.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/qmake_use.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/file_copies.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/testcase_targets.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/exceptions.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/yacc.prf:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/lex.prf:
adc_calibration.pro:
../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile adc_calibration.pro -spec devices/linux-arm-xilinx-zynq-g++ CONFIG+=debug CONFIG-=qml_debug CONFIG-=qtquickcompiler

qmake_all: FORCE


all: Makefile adc_calibration

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adc_proc.h axireg.h system_global.h $(DISTDIR)/
	$(COPY_FILE) --parents adc_proc.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/data/dummy.cpp
	/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-g++ -pipe -Wno-psabi -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/include -DZYNQ -pipe -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mfpu=vfpv3-d16 -pipe -fomit-frame-pointer --sysroot=/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot -g -std=gnu++11 -Wall -W -ffunction-sections -fdata-sections -dM -E -o moc_predefs.h ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adc_proc.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adc_proc.cpp
moc_adc_proc.cpp: adc_proc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QObject \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnamespace.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobal.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig-bootstrapped.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtcore-config.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsystemdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qprocessordetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcompilerdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtypeinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsysinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlogging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qflags.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbasicatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_bootstrap.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qgenericatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_cxx11.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_msvc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobalstatic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmutex.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnumeric.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qversiontagging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs_impl.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstring.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qchar.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qrefcount.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qarraydata.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringliteral.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringview.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringbuilder.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qiterator.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qhashfunctions.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qpair.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearraylist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qregexp.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringmatcher.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcoreevent.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qscopedpointer.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmetatype.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvarlengtharray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcontainerfwd.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject_impl.h \
		system_global.h \
		axireg.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QString \
		moc_predefs.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/moc
	/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/bin/moc $(DEFINES) --include /home/sukhval/PROJ/adc_calibration/moc_predefs.h -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/mkspecs/devices/linux-arm-xilinx-zynq-g++ -I/home/sukhval/PROJ/adc_calibration -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include -I/home/sukhval/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include adc_proc.h -o moc_adc_proc.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

adc_proc.o: adc_proc.cpp adc_proc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QObject \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnamespace.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobal.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig-bootstrapped.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtcore-config.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsystemdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qprocessordetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcompilerdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtypeinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsysinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlogging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qflags.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbasicatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_bootstrap.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qgenericatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_cxx11.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_msvc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobalstatic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmutex.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnumeric.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qversiontagging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs_impl.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstring.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qchar.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qrefcount.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qarraydata.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringliteral.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringview.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringbuilder.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qiterator.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qhashfunctions.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qpair.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearraylist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qregexp.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringmatcher.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcoreevent.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qscopedpointer.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmetatype.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvarlengtharray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcontainerfwd.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject_impl.h \
		system_global.h \
		axireg.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QString \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QDir \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qdir.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qfileinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qfile.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qfiledevice.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qiodevice.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qshareddata.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qhash.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QStringList \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QFile \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QTextStream \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtextstream.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlocale.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvariant.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmap.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qdebug.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvector.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qpoint.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qset.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcontiguouscache.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsharedpointer.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsharedpointer_impl.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QDebug \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QThread \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adc_proc.o adc_proc.cpp

main.o: main.cpp ../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QCoreApplication \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcoreapplication.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobal.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig-bootstrapped.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qconfig.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtcore-config.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsystemdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qprocessordetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcompilerdetection.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtypeinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsysinfo.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlogging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qflags.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbasicatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_bootstrap.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qgenericatomic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_cxx11.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qatomic_msvc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qglobalstatic.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmutex.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnumeric.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qversiontagging.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstring.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qchar.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qrefcount.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qnamespace.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qarraydata.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringliteral.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringview.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringbuilder.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobjectdefs_impl.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qalgorithms.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qiterator.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qhashfunctions.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qpair.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qbytearraylist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringlist.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qregexp.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qstringmatcher.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcoreevent.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qscopedpointer.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmetatype.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvarlengtharray.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcontainerfwd.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qobject_impl.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qeventloop.h \
		adc_proc.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QObject \
		system_global.h \
		axireg.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QString \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/QDebug \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qdebug.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qhash.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qmap.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qtextstream.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qiodevice.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qlocale.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvariant.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qshareddata.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qvector.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qpoint.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qset.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qcontiguouscache.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsharedpointer.h \
		../../x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/sysroot/usr/local/Qt-5.12.8/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_adc_proc.o: moc_adc_proc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adc_proc.o moc_adc_proc.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/run/user/1001/adc_calibration || mkdir -p $(INSTALL_ROOT)/run/user/1001/adc_calibration
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/run/user/1001/adc_calibration/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/run/user/1001/adc_calibration/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/run/user/1001/adc_calibration/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

